const key = 'game'
const sceneType = 'game'
export const game =  {
	id: 1,
	name: '游戏',
	key,
	icon: key,
	sort: 1,
	appList: [
	  {
		drawType: 'textToImg',
		sceneName: '像素游戏',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650e77b1b954bff35f4da5dc.jpg',
		config: {
		  prompt: '16-bit pixel art	,island in the clouds, ancient ruins,Zelda style',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '3D 游戏——场景',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650ebbe3b95482936937d2e8.jpg',
		config: {
		  prompt:
			'isometric clean pixel art	， robotics lab',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '3D 游戏——人物',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650ebbfbb95482936937d2e9.jpg',
		config: {
		  prompt:
			'blender 3d ，Dark Vader, full body, cute ，isometric ，Pixar, style of artstation',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '3D 游戏——装备',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650ebc18b95482936937d2ea.jpg',
		config: {
		  prompt: 'blender 3d ，star war, signet ring ，isometric',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	],
  }