const key = 'illustration'
const sceneType = 'illustration'
export const illustration =  {
	id: 1,
	name: '插画',
	key,
	icon: key,
	sort: 1,
	appList: [
	  {
		drawType: 'textToImg',
		sceneName: '水彩',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1705410717708021760.png',
		config: {
		  prompt: 'light watercolor,a sleeping cat,white background,Studio Ghibli',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '百科插画',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1705411261499535360.png',
		config: {
		  prompt:
			'dinosaur scientific illustration , Tyrannosaurus,white background ,Andrey Atuchin',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '绘本插画',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1705411393729163264.png',
		config: {
		  prompt:
			'illustration ,A cat standing and running on two legs in a denim jacket ,Beatrix Potter ',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: 'Behance 风科技插画',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1705411535316283392.png',
		config: {
		  prompt: 'tech illustration ,man jogging by the waterfront ,style of behance ',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '填色插画',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1705411749963984896.png',
		config: {
		  prompt: 'clean coloring book page ,Tyrannosaurus ,black and white',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	],
  }