export const logo =  {
	id: 1,
	name: 'Logo',
	key: 'logo',
	icon: 'logo',
	sort: 1,
	appList: [
	  {
		drawType: 'textToImg',
		sceneName: 'Graphic Logo',
		sceneType: 'logo',
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1697171521037934592.png',
		config: {
		  prompt: 'flat vector graphic line logo of cat, simple minimal',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: 'Lettermark Logo',
		sceneType: 'logo',
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1697172806294315008.png',
		config: {
		  prompt:
			'letter A logo, lettermark, typography, vector simple minimal',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: 'Geometric Logo',
		sceneType: 'logo',
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1697172933901819904.png',
		config: {
		  prompt:
			'Flat geometric vector geometric logo of flower, petals radial repeating, simple minimal',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: 'Mascot Logo',
		sceneType: 'logo',
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/1697173072959774720.png',
		config: {
		  prompt: 'simple mascot logo for a Instant Noodles company',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	],
  }