const key = 'other'
const sceneType = 'other'
export const other =  {
	id: 1,
	name: '其他',
	key,
	icon: key,
	sort: 1,
	appList: [
	  {
		drawType: 'textToImg',
		sceneName: '贴纸',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650ec384b95482936937d2f2.jpeg',
		config: {
		  prompt: 'sticker，Stormtrooper, cute	，vector',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '剪纸',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650ec392b95482936937d2f3.jpeg',
		config: {
		  prompt:
			'layered paper art	，Death Star, shadowbox, volumetric lighting',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '邮票',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650ec3a9b95482936937d2f4.jpeg',
		config: {
		  prompt:
			'vintage postage stamp	,Stormtrooper, red ink,	line engraving, intaglio',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	  {
		drawType: 'textToImg',
		sceneName: '海报',
		sceneType,
		url: 'https://sia-font.oss-cn-beijing.aliyuncs.com/images/650ec3d6b95482936937d2f5.jpeg',
		config: {
		  prompt: 'movie poster	,Star War	,studio ghibli, retro anime',
		  model: 'mj',
		  cus: false,
		  ar: '1:1',
		  chaos: 0,
		  s: 0,
		  q: 0.25,
		  tile: false,
		  v: 5.2,
		  images: [],
		  isPublic: false,
		},
	  },
	],
  }