const routes = [
  {
    path: '/',
    redirect: '/ai/chat',
  },
  {
    path: '/ai',
    redirect: '/ai/chat',
  },
  {
    path: '/login',
    component: './Login',
  },
  {
    name: 'ai',
    path: '/ai',
    component: './Ai',
    routes: [
      { path: '/ai/chat', component: './Ai/Chat' },
      { path: '/ai/app', component: './Ai/AppContent'},
      { path: '/ai/draw', component: './Ai/Draw' },
      { path: '/ai/app-generate', component: './Ai/AppGenerate' },
      { path: '/ai/gallery', component: './Ai/Gallery' },
      { path: '/ai/iframe', component: './Ai/Iframe' },
      { path: '/ai/tools', component: './Ai/AiTools' },
      { path: '/ai/tools/chat-doc', component: './Ai/ChatDoc' },
      { path: '/ai/tools/chat-doc/files', component: './Ai/ChatDoc/ChatDocFiles' },
      {
        path: '/ai/me',
        component: './Ai/Me',
        routes: [
          { path: '/ai/me/profile', component: './Ai/Me/Profile' },
          { path: '/ai/me/plan', component: './Ai/Me/Plan' },
          { path: '/ai/me/product', component: './Ai/Me/Product' },
          { path: '/ai/me/invite', component: './Ai/Me/Invite' },
          { path: '/ai/me/security', component: './Ai/Me/Security' },
        ],
      },
    ],
  },
  {
    name: 'admin',
    path: '/admin',
    component: './Admin',
	wrappers: [
        '@/wrappers/auth',
    ],
	routes: [
		{ path: '/admin/panel', component: './Admin/Panel'},
		{ path: '/admin/chat/chat', component: './Admin/ChatMana/index' },
		{ path: '/admin/chat/message', component: './Admin/ChatMana/Message' },
		{ path: '/admin/chat/pool', component: './Admin/ChatMana/ChatPool' },
		{ path: '/admin/draw/draw', component: './Admin/DrawMana' },
		{ path: '/admin/draw/pool', component: './Admin/DrawMana/DrawPool' },
		{ path: '/admin/user/user', component: './Admin/UserMana' },
		{ path: '/admin/user/plan', component: './Admin/UserMana/UserPlan' },
		{ path: '/admin/plan/plan', component: './Admin/PlanMana' },
		{ path: '/admin/plan/class', component: './Admin/PlanMana/ClassMana' },
		{ path: '/admin/order', component: './Admin/OrderMana' },
		{ path: '/admin/exChangeCode', component: './Admin/ExchangeCode' },
		{ path: '/admin/content', component: './Admin/ContentMana' },
		{ path: '/admin/app', component: './Admin/AppMana' },
		{ path: '/admin/class', component: './Admin/ClassMana' },
		{ path: '/admin/site/global', component: './Admin/SiteMana/Global' },
		{ path: '/admin/site/chat', component: './Admin/SiteMana/Chat' },
		{ path: '/admin/site/draw', component: './Admin/SiteMana/Draw' },
		{ path: '/admin/site/menus', component: './Admin/SiteMana/Menus' },
		{ path: '/admin/site/content', component: './Admin/SiteMana/Content' },
		{ path: '/admin/site/protocol', component: './Admin/SiteMana/Protocol' },
		{ path: '/admin/site/security', component: './Admin/SiteMana/Security' },
		{ path: '/admin/site/authorization-activation', component: './Admin/SiteMana/AuthorizationActivation' },
	  ],
  },
  { path: '/901', component: './Error/501' },
  { path: '/*', component: './Error/404' },
];
export default routes;
